#!/usr/bin/env bash
# SessionStart hook: install development tools when running in Claude Code on the web.
# Idempotent: each tool is skipped if already on PATH.
# Generated by /configure-plugin:configure-web-session.
set -euo pipefail

if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  echo "[install_pkgs] Not a remote environment, skipping."
  exit 0
fi

INSTALL_DIR="/usr/local/bin"

has() { command -v "$1" >/dev/null 2>&1; }

# --- pre-commit (via pip) ---
if ! has pre-commit; then
  echo "[install_pkgs] Installing pre-commit..."
  pip install --quiet pre-commit
else
  echo "[install_pkgs] pre-commit already installed, skipping."
fi

# --- actionlint 1.7.7 (pinned to .pre-commit-config.yaml) ---
ACTIONLINT_VERSION="1.7.7"
if ! has actionlint; then
  echo "[install_pkgs] Installing actionlint ${ACTIONLINT_VERSION}..."
  tmpdir=$(mktemp -d)
  curl -fsSL "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz" | tar xz -C "${tmpdir}" actionlint
  mv "${tmpdir}/actionlint" "${INSTALL_DIR}/actionlint"
  chmod +x "${INSTALL_DIR}/actionlint"
  rm -rf "${tmpdir}"
else
  echo "[install_pkgs] actionlint already installed, skipping."
fi

# --- Summary ---
echo "[install_pkgs] Done. Available tools:"
for cmd in pre-commit actionlint ; do
  if has "$cmd"; then
    echo "  $cmd: $(command -v "$cmd")"
  else
    echo "  $cmd: NOT FOUND (install failed)"
  fi
done
